# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

language: python
#group: travis_latest
os: linux
#dist: bionic

git:
  depth: 20

# blas and openblas from APT is much slower than "sudo apt-get -qq install"
#addons:
#  apt:
#    packages:
#    - gcc
#    - g++
#    - gfortran
#    - libblas-dev
#    - curl
#    - cmake

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

cache:
  apt: true
  pip: true

before_install:
  - sudo apt-get -qq install gcc gfortran libgfortran3 libblas-dev cmake curl
  - pip install "numpy!=1.16,!=1.17" "scipy<1.5" h5py nose nose-exclude nose-timer codecov

install:
  # openblas from numpy may be slightly faster than the default libblas library
  #- cd $TRAVIS_BUILD_DIR/pyscf/lib &&
  #  ln -s `python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"`/.libs/lib* ./ &&
  #  blaslib=`basename libopenblas* .so | cut -c 4-` &&
  #  echo 'set(BLAS_LIBRARIES "-L${PROJECT_SOURCE_DIR} -l'${blaslib}'")' > cmake.arch.inc
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    curl http://www.sunqm.net/pyscf/files/bin/pyscf-1.7-deps.tar.gz | tar xzf -
  - pip install pyberny geometric
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 && $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install git+https://github.com/maxscheurer/cppe.git; fi
  - cd $TRAVIS_BUILD_DIR/pyscf/lib &&
    mkdir build &&
    cd build &&
    cmake -DBUILD_LIBXC=OFF -DBUILD_XCFUN=OFF .. &&
    make &&
    cd ../..

before_script:
  - rm $TRAVIS_BUILD_DIR/pyscf/pbc/tools/pyscf_ase.py

script:
  - cd $TRAVIS_BUILD_DIR/pyscf &&
    echo 'pbc_tools_pbc_fft_engine = "NUMPY"' > pyscf_config.py &&
    echo "dftd3_DFTD3PATH = '$TRAVIS_BUILD_DIR/pyscf/lib/deps/lib'" >> pyscf_config.py
  - OMP_NUM_THREADS=1 PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH PYSCF_CONFIG_FILE=$(pwd)/pyscf_config.py
    nosetests -v --with-timer --with-coverage
    --exclude-dir=dmrgscf --exclude-dir=fciqmcscf
    --exclude-dir=icmpspt --exclude-dir=shciscf --exclude-dir=examples --exclude-dir=nao
    --exclude-dir=cornell_shci --exclude-dir=pbc/grad
    -e test_bz
    -e h2o_vdz
    -e test_mc2step_4o4e
    -e test_ks_noimport
    -e test_jk_single_kpt
    -e test_jk_hermi0
    -e test_j_kpts
    -e test_k_kpts
    -e high_cost
    -e skip
    -e call_in_background
    -e libxc_cam_beta_bug
    -e test_finite_diff_rks_eph
    -e test_finite_diff_uks_eph
    -I test_kuccsd_supercell_vs_kpts\.py
    -I test_kccsd_ghf\.py
    -I test_h_.*\.py
    -I test_P_uadc_ea.py
    -I test_P_uadc_ip.py
    --exclude-test=pbc/gw/test/test_kgw_slow_supercell.DiamondTestSupercell3
    --exclude-test=pbc/gw/test/test_kgw_slow_supercell.DiamondKSTestSupercell3
    --exclude-test=pbc/gw/test/test_kgw_slow.DiamondTestSupercell3
    --exclude-test=pbc/gw/test/test_kgw_slow.DiamondKSTestSupercell3
    --exclude-test=pbc/tdscf/test/test_krhf_slow_supercell.DiamondTestSupercell3
    --exclude-test=pbc/tdscf/test/test_kproxy_hf.DiamondTestSupercell3
    --exclude-test=pbc/tdscf/test/test_kproxy_ks.DiamondTestSupercell3
    --exclude-test=pbc/tdscf/test/test_kproxy_supercell_hf.DiamondTestSupercell3
    --exclude-test=pbc/tdscf/test/test_kproxy_supercell_ks.DiamondTestSupercell3
    -I .*_slow.*py -I .*_kproxy_.*py -I test_proxy.py # tdscf/*_slow.py gw/*_slow.py do not compatible with python3.[456] and old numpy

after_success:
  - codecov
